In [35]:
import pandas as pd
import plotly.offline as po

import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot

In [19]:
import plotly.plotly as po

In [4]:
# method for making the graphs 
def gen_graph(df, graph_type, agg_var):
    if graph_type == 'bar_graph':
        total_injured_by_county = pd.pivot_table(df, values='People Injured', index='County',aggfunc=agg_var)
        total_unitsAffected_by_county = pd.pivot_table(df, values='Units Affected', index='County',aggfunc=agg_var)
        trace_injured = go.Bar(
            x = list(total_injured_by_county.index), 
            y = list(total_injured_by_county.values), 
            name = 'People Injured'
        )
        trace_unitsAffected = go.Bar(
            x = list(total_unitsAffected_by_county.index),
            y = list(total_unitsAffected_by_county.values),
            name = 'Units Affected'
        )
        my_data = [trace_injured,trace_unitsAffected]
        my_layout = go.Layout(barmode = 'group')
        fig = go.Figure(data = my_data, layout = my_layout)

        po.plot(fig,filename = 'testing2.html')

In [40]:
# avg adults and children per incident in given df (pie chart). Allows volunteer to see the demographic of people living 
# in the area (more children or more adults, indication of family)


def gen_people_avg(df):
    adults_mean = df['Adults'].mean()
    children_mean = df["Children"].mean()
    
    categories = ['Adults','Children']
    
    vals = [adults_mean, children_mean]

    trace = go.Pie(labels = categories, values = vals)
    
    po.plot([trace])

In [41]:
gen_people_avg(df)

In [10]:
df = pd.read_csv('C:/Users/Elliot/GitHub/ARC_After_Fire_Reports/data/Incidents_Clean.csv')

In [8]:
gen_graph(df, 'bar_graph', 'sum')

In [ ]:
family1 = pd.pivot_table(df,values='Assistance', index='Families')

In [43]:
#filter
fam_names=df.Families.unique()
fam_names

    

single_family_df = df[df.Families==1]
small_family_df = df[(df.Families<=5) & (df.Families >=2)]
larger_family_df = df[df.Families>5]

In [44]:
fam_names

array([ 5.,  1.,  0.,  2.,  4.,  3.,  7., 19.,  6., 10.,  8.,  9., 22.,
       32., 12., 16., 39., 15., 14., 11., 25., 13., 20., 18., 17., 50.,
       31., 23., 21., 40., 43., 57.])

In [41]:
single_family_df

,Unnamed: 0,Date,Incident Number,Incident Call Type,Event Number,Status,Address,City,State,Zip,...,Assistance,Verified,Relayed,Identified,Arrived,Departed,Verify_to_Relay,Relay_to_Identification,Identification_to_Arrival,Arrival_to_Departure
1,5,2014-01-01,14-0535,hot,1-1F6ATB,closed,18405 REGAL ROAD,HOMEWOOD,IL,60430.0,...,0.0,2014-01-01 16:05:00,2014-01-01 16:20:00,2014-12-30 20:13:00,2014-01-01 17:30:00,2014-01-01 18:10:00,0 days 00:15:00.000000000,363 days 03:53:00.000000000,-364 days +21:17:00.000000000,0 days 00:40:00.000000000
2,7,2014-01-01,14-0536,hot,1-1F6ATV,closed,4323 SOUTH DEARBORN,CHICAGO,IL,60609.0,...,0.0,2014-01-01 21:10:00,2014-01-01 21:15:00,2014-01-01 21:50:00,2014-01-01 22:59:00,2014-01-01 23:51:00,0 days 00:05:00.000000000,0 days 00:35:00.000000000,0 days 01:09:00.000000000,0 days 00:52:00.000000000
6,15,2014-01-02,14-0540,hot,1-1F76MJ,closed,131 S 9TH AVE,MAYWOOD,IL,60153.0,...,0.0,2014-01-02 22:45:00,2014-01-02 22:59:00,2014-01-02 23:38:00,2014-01-03 00:00:00,2014-01-03 01:41:00,0 days 00:14:00.000000000,0 days 00:39:00.000000000,0 days 00:22:00.000000000,0 days 01:41:00.000000000
10,23,2014-01-03,14-0544,NaN,1-1F76ON,closed,2123 TENNESSEE,GARY,IL,46407.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,35,2014-01-05,14-0550,NaN,1-1F7B9N,closed,828 North 3rd Avenue,St. Charles,IL,63301.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,39,2014-01-05,14-0552,NaN,1-1F7G3J,closed,309 DELLWOOD AVE,LOCKPORT,IL,60441.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,41,2014-01-05,14-0553,NaN,1-1F7G47,closed,2757 S Keeler Ave.,CHICAGO,IL,60623.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,43,2014-01-07,14-0554,NaN,1-1F9PUH,closed,8492 W 4000N Rd,BONFIELD,IL,60913.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,47,2014-01-08,14-0556,NaN,1-1FA6JL,closed,644 SIBLEY ST,HAMMOND,IN,46320.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,55,2014-01-07,14-0560,NaN,1-1F94VH,closed,1405 N ARTHUR BURCH DR,BOURBONNAIS,IL,60914.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,59,2014-01-07,14-0562,NaN,1-1F84AT,closed,421 S TANNER,KANKAKEE,IL,60901.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,61,2014-01-07,14-0563,NaN,1-1F94W7,closed,3141 W 139TH PL,ROBBINS,IL,60472.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,65,2014-01-07,14-0565,NaN,1-1FA9ZZ,closed,8245 W BELMONT AVE,RIVER GROVE,IL,60634.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,71,2014-01-07,14-0568,NaN,1-1FAA1O,closed,1793 MCCORMICK LN,HANOVER PARK,IL,60133.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,75,2014-01-08,14-0570,NaN,1-1FAA2J,closed,1216 CHIPPEWA STREET,JOLIET,IL,60433.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,77,2014-01-08,14-0571,NaN,1-1FAA39,closed,8643 S HOUSTON,CHICAGO,IL,60617.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,79,2014-01-08,14-0572,NaN,1-1FAA3T,closed,12210 W JOLIET ROAD,MANHATTAN,IL,60442.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,81,2014-01-08,14-0573,NaN,1-1FAA4H,closed,300 N WILLOW PIKE ROAD,AROMA PARK,IL,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,83,2014-01-08,14-0574,NaN,1-1FACOY,closed,7944 S. MOZART,CHICAGO,IL,60652.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,97,2014-01-09,14-0581,NaN,1-1FAHXV,closed,3656 W GEORGE ST,CHICAGO,IL,60618.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,109,2014-01-10,14-0587,NaN,1-1FB42F,closed,6037 W. 29TH PLACE,GARY,IN,46406.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,113,2014-01-10,14-0589,NaN,1-1FAHYH,closed,5927 S THROOP ST,CHICAGO,IL,60636.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,115,2014-01-10,14-0590,NaN,1-1FAHYX,closed,126 E 119TH PL,CHICAGO,IL,60628.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,121,2014-01-11,14-0593,NaN,1-1FAHZV,closed,5841 W 245TH AVE,"LOWELL, IN",IN,46356.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,123,2014-01-11,14-0594,NaN,1-1FAHZJ,closed,9335 S LAFLIN ST,CHICAGO,IL,60620.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,131,2014-01-12,14-0598,NaN,1-1FAIRZ,closed,13233 E 2500 SOUTH ROAD,PEMBROKE TWNSHP,IL,60954.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,133,2014-01-13,14-0599,NaN,1-1FAJ4R,closed,13028 S KING DR,CHICAGO,IL,60827.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,137,2014-01-14,14-0601,NaN,1-1FBOCX,closed,8849 S INDIANA,CHICAGO,IL,60619.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,139,2014-01-14,14-0602,NaN,1-1FBODL,closed,7838 S LANGLEY,CHICAGO,IL,60619.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,141,2014-01-14,14-0603,NaN,1-1FBOE7,closed,2425 ARTHUR,GARY,IN,46404.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5632,25625,2018-08-10,19-0331,hot,ZZ0818-FIR-60,closed,4419 W Fullerton Ave,Chicago,IL,60639.0,...,0.0,2018-08-11 04:15:00,2018-08-11 04:16:00,2018-08-11 04:23:00,2018-08-11 04:59:00,2018-08-11 05:55:00,0 days 00:01:00.000000000,0 days 00:07:00.000000000,0 days 00:36:00.000000000,0 days 00:56:00.000000000
5634,25633,2018-08-11,19-0335,hot,IL0818-FIR-60,closed,3115 W Fillmore St,Chicago,IL,60612.0,...,250.0,2018-08-12 04:13:00,2018-08-12 04:14:00,2018-08-12 04:16:00,NaN,2018-08-12 05:08:00,0 days 00:01:00.000000000,0 days 00:02:00.000000000,NaN,NaN
5635,25639,2018-08-12,19-0338,hot,IL0818-FIR-61,closed,1925 S 8th Ave,Maywood,IL,60153.0,...,780.0,2018-08-12 07:16:00,2018-08-12 07:17:00,2018-08-12 07:37:00,2019-07-12 06:23:30,2018-08-12 09:36:00,0 days 00:01:00.000000000,0 days 00:20:00.000000000,333 days 22:46:30.000000000,-334 days +03:12:30.000000000
5636,25641,2018-08-12,19-0339,cold,IL0818-FIR-62,closed,146 Flamingo Dr,Beecher,IL,60401.0,...,405.0,2018-08-12 12:30:00,2018-08-12 12:31:00,2018-08-12 13:40:00,2018-08-12 15:34:00,2018-08-12 16:29:00,0 days 00:01:00.000000000,0 days 01:09:00.000000000,0 days 01:54:00.000000000,0 days 00:55:00.000000000
5638,25653,2018-08-13,19-0345,hot,IL0818-FIR-68,closed,7801 S Clyde Ave,Chicago,IL,60649.0,...,405.0,2018-08-13 19:29:00,2018-08-13 19:31:00,2018-08-13 19:44:00,2018-08-13 20:46:00,2018-08-13 21:43:00,0 days 00:02:00.000000000,0 days 00:13:00.000000000,0 days 01:02:00.000000000,0 days 00:57:00.000000000
5639,25657,2018-08-13,19-0347,hot,IL0818-FIR-72,closed,34347 Juneway Ave,Wilmington,IL,60481.0,...,530.0,2018-08-13 22:34:00,2018-08-13 22:50:00,2018-08-13 22:56:00,NaN,2018-08-14 00:58:00,0 days 00:16:00.000000000,0 days 00:06:00.000000000,NaN,NaN
5640,25663,2018-08-14,19-0350,hot,IL0818-FIR-74,closed,2632 W Greenwood Ave,Waukegan,IL,60087.0,...,1715.0,2018-08-14 05:14:00,2018-08-14 05:14:00,2018-08-14 05:30:00,2019-07-12 21:17:12,2018-08-14 07:18:00,0 days 00:00:00.000000000,0 days 00:16:00.000000000,332 days 15:47:12.000000000,-333 days +10:00:48.000000000
5642,25677,2018-08-15,19-0357,hot,IL0818-FIR-76,closed,8112 S Evans Ave,Chicago,IL,60619.0,...,409.0,2018-08-15 06:13:00,2018-08-15 06:16:00,2018-08-15 06:25:00,2019-07-12 19:19:36,2018-08-15 08:45:00,0 days 00:03:00.000000000,0 days 00:09:00.000000000,331 days 12:54:36.000000000,-332 days +13:25:24.000000000
5643,25687,2018-08-15,19-0362,hot,L0818-FIR-79,closed,7634 S Ada St,Chicago,IL,60620.0,...,1055.0,2018-08-16 03:09:00,2018-08-16 03:29:00,2018-08-16 03:37:00,2019-07-12 20:33:48,2018-08-16 05:31:00,0 days 00:20:00.000000000,0 days 00:08:00.000000000,330 days 16:56:48.000000000,-331 days +08:57:12.000000000
5645,25691,2018-08-16,19-0364,hot,IL0818-FIR-83,closed,110 Minton Rd,Joliet,IL,60436.0,...,530.0,2018-08-16 23:45:00,2018-08-16 23:55:00,2018-08-17 00:11:00,2018-08-17 01:06:00,2018-08-17 03:00:00,0 days 00:10:00.000000000,0 days 00:16:00.000000000,0 days 00:55:00.000000000,0 days 01:54:00.000000000
5646,25693,2018-08-16,19-0365,hot,IL0818-FIR-82,closed,2905 Park Terrace Dr,Rockford,IL,61114.0,...,1090.0,2018-08-17 00:48:00,2018-08-17 00:49:00,2018-08-17 01:00:00,2018-08-17 02:08:00,2018-08-17 02:34:00,0 days 00:01:00.000000000,0 days 00:11:00.000000000,0 days 01:08:00.000000000,0 days 00:26:00.000000000
5647,25695,2018-08-16,19-0366,hot,IL0818-FIR-84,closed,3937 W 82nd Pl,Chicago,IL,60652.0,...,780.0,2018-08-17 02:42:00,2018-08-17 02:43:00,2018-08-17 02:48:00,NaN,2018-08-17 05:04:00,0 days 00:01:00.000000000,0 days 00:05:00.000000000,NaN,NaN
5649,25701,2018-08-17,19-0369,hot,26395619,closed,7712 S Winchester Ave,Chicago,IL,60620.0,...,200.0,2018-08-18 00:20:00,2018-08-18 00:21:00,2018-08-18 00:32:00,2018-08-18 02:00:00,2018-08-18 02:50:00,0 days 00:01:00.000000000,0 days 00:11:00.000000000,0 days 01:28:00.000000000,0 days 00:50:00.000000000
5650,25709,2018-08-18,19-0373,hot,NaN,closed,6330 N Oketo Ave,Chicago,IL,60631.0,...,0.0,2018-08-19 02:18:00,2018-08-19 02:19:00,2018-08-19 02:25:00,NaN,NaN,0 days 00:01:00.000000000,0 days 00:06:00.000000000,NaN,NaN
5653,25719,2018-08-19,19-0378,hot,IL0818-FIR-96,closed,811 Pearl St,Aurora,IL,60505.0,...,780.0,2018-08-20 00:45:00,2018-08-20 01:19:00,2018-08-20 01:39:00,2018-08-20 03:05:00,2018-08-20 04:00:00,0 days 00:34:00.000000000,0 days 00:20:00.000000000,0 days 01:26:00.000000000,0 days 00:55:00.000000000
5656,25733,2018-08-21,19-0385,hot,IL 08/18 FIR 101,closed,6105 W Giddings St,Chicago,IL,60630.0,...,405.0,2018-08-21 08:21:00,2018-08-21 11:57:00,2018-08-21 12:26:00,2018-08-21 13:16:00,2018-08-21 13:56:00,0 days 03:36:00.000000000,0 days 00:29:00.000000000,0 days 00:50:00.000000000,0 days 00:40:00.000000000
5657,25735,2018-08-21,19-0386,hot,IL 08/18 Fire 102,closed,55 W 104th Pl,Chicago,IL,60628.0,...,1185.0,2018-08-21 11:57:00,2018-08-21 11:57:00,2018-08-21 12:28:00,2018-08-21 13:12:00,2018-08-21 14:43:00,0 days 00:00:00.000000000,0 days 00:31:00.000000000,0 days 00:44:00.000000000,0 days 01:31:00.000000000
5659,25747,2018-08-23,19-0392,hot,IL 08/18 Fire 109,closed,5615 S Albany Ave,Chicago,IL,60629.0,...,1185.0,2018-08-23 10:12:00,2018-08-23 10:13:00,2018-08-23 11:29:00,2019-07-12 21:57:12,2018-08-23 13:41:00,0 days 00:01:00.000000000,0 days 01:16:00.000000000,323 days 10:28:12.000000000,-324 days +15:43:48.000000000
5660,25749,2018-08-23,19-0393,hot,IL08/18Fire108,closed,3434 W 160th St,Markham,IL,60428.0,...,1310.0,2018-08-23 10:54:00,2018-08-23 10:55:00,2018-08-23 11:31:00,NaN,2018-08-23 14:00:00,0 days 00:01:00.000000000,0 days 00:36:00.000000000,NaN,NaN
5661,25753,2018-08-24,19-0395,cold,IL0818-FIR-135,closed,13301 S Old Western Ave,Blue Island,IL,60406.0,...,1264.0,2018-08-24 08:37:00,2018-08-29 17:07:00,2018-08-29 17:21:00,2018-08-29 18:53:00,2018-08-29 18:53:00,5 days 08:30:00.000000000,0 days 00:14:00.000000000,0 days 01:32:00.000000000,0 days 00:00:00.000000000
5664,25765,2018-08-26,19-0401,hot,IL0818-FIR-125,closed,48 Woodland Glen,Park Forest,IL,60466.0,...,1435.0,2018-08-26 19:57:00,2018-08-26 20:00:00,2018-08-26 20:17:00,2018-08-26 21:07:00,2018-08-26 21:55:00,0 days 00:03:00.000000000,0 days 00:17:00.000000000,0 days 00:50:00.000000000,0 days 00:48:00.000000000
5667,25773,2018-08-27,19-0405,hot,NaN,closed,430 Kickapoo Ave,Batavia,IL,60510.0,...,0.0,2018-08-27 12:37:00,2018-08-27 13:11:00,2018-08-27 13:22:00,2018-08-27 14:26:00,2018-08-27 14:58:00,0 days 00:34:00.000000000,0 days 00:11:00.000000000,0 days 01:04:00.000000000,0 days 00:32:00.000000000
5668,25775,2018-08-27,19-0406,hot,IL 08/18 FIR128,closed,9901 S Wood St,Chicago,IL,60643.0,...,1185.0,2018-08-27 14:33:00,2018-08-27 14:47:00,2018-08-27 14:52:00,2018-08-27 16:00:00,2018-08-27 16:50:00,0 days 00:14:00.000000000,0 days 00:05:00.000000000,0 days 01:08:00.000000000,0 days 00:50:00.000000000
5670,25785,2018-08-28,19-0411,hot,IL0818-FIR-132,closed,415 Upham Pl,Dixon,IL,61021.0,...,670.0,2018-08-28 06:34:00,2018-08-28 06:35:00,2018-08-28 06:58:00,NaN,2018-08-28 08:11:00,0 days 00:01:00.000000000,0 days 00:23:00.000000000,NaN,NaN
5671,25793,2018-08-28,19-0415,cold,26431219,closed,4904 S Kolin Ave,Chicago,IL,60632.0,...,780.0,2018-08-29 03:32:00,2018-08-29 20:00:00,2018-08-29 20:00:00,2018-08-29 20:00:00,2018-08-29 20:55:00,0 days 16:28:00.000000000,0 days 00:00:00.000000000,0 days 00:00:00.000000000,0 days 00:55:00.000000000
5672,25803,2018-08-29,19-0420,hot,IL0818-FIR-137,closed,1315 Modaff Rd,Naperville,IL,60540.0,...,405.0,2018-08-29 19:10:00,2018-08-29 19:12:00,2018-08-29 19:24:00,2018-08-29 20:05:00,2018-08-29 20:59:00,0 days 00:02:00.000000000,0 days 00:12:00.000000000,0 days 00:41:00.000000000,0 days 00:54:00.000000000
5675,25811,2018-08-30,19-0424,hot,NaN,closed,311 W 106th St,Chicago,IL,60628.0,...,875.0,2018-08-30 18:39:00,2018-08-30 19:30:00,2018-08-30 19:32:00,2018-08-30 20:35:00,2018-08-30 21:36:00,0 days 00:51:00.000000000,0 days 00:02:00.000000000,0 days 01:03:00.000000000,0 days 01:01:00.000000000
5676,25813,2018-08-30,19-0425,hot,IL0818-FIR-142,closed,827 Hoban Ave,Rockford,IL,61101.0,...,965.0,2018-08-30 20:18:00,2018-08-30 20:22:00,2018-08-30 20:26:00,2018-08-30 20:43:00,2018-08-30 21:55:00,0 days 00:04:00.000000000,0 days 00:04:00.000000000,0 days 00:17:00.000000000,0 days 01:12:00.000000000
5678,25821,2018-08-31,19-0429,hot,IL0818-FIR-148,closed,6520 S University Ave,Chicago,IL,60637.0,...,920.0,2018-08-31 15:07:00,2018-08-31 15:08:00,2018-08-31 15:12:00,2018-08-31 16:13:00,2018-08-31 16:43:00,0 days 00:01:00.000000000,0 days 00:04:00.000000000,0 days 01:01:00.000000000,0 days 00:30:00.000000000
5680,25825,2018-08-31,19-0431,hot,IL0918-FIR-2,closed,723 N Christiana Ave,Chicago,IL,60624.0,...,1095.0,2018-09-01 04:51:00,2018-09-01 04:52:00,2018-09-01 05:02:00,2018-09-01 05:16:00,2018-09-01 06:13:00,0 days 00:01:00.000000000,0 days 00:10:00.000000000,0 days 00:14:00.000000000,0 days 00:57:00.000000000

In [45]:

total_injured_by_county = pd.pivot_table(df, values='People Injured', index='County',aggfunc='sum')

In [46]:
total_unitsAffected_by_county = pd.pivot_table(df, values='Units Affected', index='County',aggfunc='sum')

In [47]:
test1 = total_adults_by_county.head()

In [48]:
total_unitsAffected_by_county

            Units Affected
County
Boone                   28
Bureau                   6
Carroll                  2
Cook                  1585
DeKalb                   8
Dekalb                   2
DuPage                 135
Dubuque                  0
Dupage                   0
Grundy                   1
Jo Daviess               1
Kane                    62
Kankakee                17
Kendall                  0
LaSalle                 22
Lake                    60
Lee                      5
Livingston               0
Marshall                 0
McHenry                 25
Newton                   0
Ogle                    17
Putnam                   0
Stephenson               2
Walworth                 0
Whiteside                1
Will                   130
Winnebago               51

In [49]:
total_injured_by_county

            People Injured
County
Boone                   15
Bureau                   0
Carroll                  1
Cook                   395
DeKalb                   2
Dekalb                   1
DuPage                  10
Dubuque                  0
Dupage                   0
Grundy                   0
Jo Daviess               2
Kane                     9
Kankakee                 6
Kendall                  0
LaSalle                  4
Lake                    26
Lee                      2
Livingston               0
Marshall                 0
McHenry                  4
Newton                   0
Ogle                     1
Putnam                   0
Stephenson               2
Walworth                 0
Whiteside                3
Will                     9
Winnebago               16

In [53]:
trace_injured = go.Bar(
    x = list(total_injured_by_county.index), 
    y = list(total_injured_by_county.values), 
    name = 'People Injured'
    )
trace_unitsAffected = go.Bar(
    x = list(total_unitsAffected_by_county.index),
    y = list(total_unitsAffected_by_county.values),
    name = 'Units Affected'
    )
my_data = [trace_injured,trace_unitsAffected]
my_layout = go.Layout(barmode = 'stack')
fig = go.Figure(data = my_data, layout = my_layout)
po.iplot(fig)
po.iplot(my_data,filename = 'testing')